Algoritmo "comando de saída"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/06/2025
Var



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Escreva qualquer coisa")
escreva ("Escreva qualquer coisa")


Fimalgoritmo