Algoritmo "CondicionalSimples"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/06/2025
Var
// Seção de Declarações das variáveis 
dinheiro: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
dinheiro <- 10000

se(dinheiro >= 1000)entao
escreva("vai")
fimse
Fimalgoritmo