Algoritmo "MeuNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/06/2025
Var
// Seção de Declarações das variáveis 
nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
nome <- "Paulo Ribeiro de Aguiar"
escreva ("Muito Prazer ", nome)

Fimalgoritmo