Algoritmo "TabuadaPara"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/06/2025
Var
// Seção de Declarações das variáveis
contador: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para contador <- 1 ate 10 faca
     escreval(contador," X ", )
     fimpara
Fimalgoritmo